customslider.settings:
  type: config_object
  label: 'Custom Slider Settings'
  mapping:
    next:
      type: text
      label: 'Next label text value'
    previous:
      type: text
      label: 'Previous label text value'
